### PR TITLE
ethernetaddr.hh: adding all missed functions.

### PR DESCRIPTION
**Pull request by vitalivanov**
Issue #12.

ethernetaddr.cc module is not compiled in for now. Thus there are
possibilities to have undefined references. Moving all required methods
to header file and removing source module completely.
Small styling cleanups.

### CODE REVIEW

**Comment by vitalivanov** [comment]
tootoonchian, any news on this?

**Comment by tootoonchian** [comment]
I'm fine with making it header only. You could perhaps move the helper functions to an anonymous namespace.

**Comment by vitalivanov** [comment]
Do you wanna move:
static int hexit_value(int c);
to global namespace? I do not see a reason for this at least for now.
Other methods like:
inline std::size_t hash_value(const ethernetaddr& ethaddr);
are also under vigil namespace right now.
If you insist I can do this..

**Comment by tootoonchian** [comment]
I meant to put it in an unnamed namespace. See
http://stackoverflow.com/questions/357404/why-are-unnamed-namespaces-used-and-what-are-their-benefits
and
let me know if it makes sense.

**Comment by vitalivanov** [comment]
Oh, you mean 'static' identifier...
Method hexit_value should have internal linkage as it's not supposed to be used anywhere else.
If there is such a need in future it can be changed.

unnamed namespace will make it to have external linkage. Size of lib would be bigger.

I propose to make it static inline.

static inline int hexit_value(int c);

Your thoughts?

**Comment by tootoonchian** [comment]
No, I don't mean a static declaration :-)

This type of static declarations is deprecated (see C++ standard, article
7.3.1.1) and unnamed namespaces should be used instead.

Amin

**Comment by vitalivanov** [comment]
Moved hexit_value method to unnamed namespace.

**Pull request merged**
